### ISSUE TITLE
Content of clipping gets deleted

### ISSUE THREAD

**Issue by deladriere** [florian42/obsidian-clipper#10]
The script launches and generates a page containing all the relevant information. 
However, the content of the note is only visible for a brief period (around one second) before its content gets deleted.
Working with  Obsidian 1.4.14 on Chrome Version 117.0.5938.149 (Build officiel) on MacOS 13.6

**Comment by florian42** [comment]
Hi @deladriere, does this happen only for a specific website or for all? Would it be possible to list the plugins you have installed?

**Comment by deladriere** [comment]
Sorry but its working again
