### ISSUE TITLE
Option removing special characters from title

### ISSUE THREAD

**Issue by chrisoutwright** [florian42/obsidian-clipper#13]
Is there a way to set a replacement strategy on the title for clippings? File name restriction are preventing the clippings in being created

**Comment by florian42** [comment]
@chrisoutwright thanks for reporting this. There is already a [replacement strategy in place](https://github.com/florian42/obsidian-clipper/blob/0576d6c3d2e24cb93ed3cf426d67d9677f284610/src/contentScript.ts#L24). Can you provide me with a website where this doesn't work?
Which OS are you using?

**Comment by florian42** [comment]
Closed due to lack of response. However I might have found the issue in #19. When there are multiple `:` in the title only the first occurrence was replaced. Now all are replaced properly.
